spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true

  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    username: sokdakX2@gmail.com
    password: ENC(zujQhI+ZcjpcofWkg+bV8JrASmLVjUia0kUHDQC103I=)
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length:
        access: 3600000
        refresh: 1210000000

logging:
  level:
    org:
      hibernate:
        type: trace

server:
  servlet:
    session:
      cookie:
        http-only: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
