= 속닥속닥 API 명세
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:sectnums:
:docinfo: shared-head

== 메인페이지

=== 메인페이지 조회
==== 성공
operation::board/find/content[snippets='http-request,http-response']

== 회원가입

=== 이메일 인증
==== 성공
operation::member/email/success[snippets='http-request,http-response']
==== 실패
===== 우테코 크루가 아닌 경우
operation::member/email/fail/noWooteco[snippets='http-request,http-response']
===== 가입한 우테코 크루인 경우
operation::member/email/fail/alreadySignUp[snippets='http-request,http-response']

=== 인증번호 확인
==== 성공
operation::member/verification/success[snippets='http-request,http-response']
==== 실패
===== 잘못되었거나 만료된 인증번호인 경우
operation::member/verification/fail[snippets='http-request,http-response']


=== 아이디 중복 확인
==== 성공
===== 고유한 아이디인 경우
operation::member/uniqueId/success/true[snippets='http-request,http-response']
===== 중복된 아이디인 경우
operation::member/uniqueId/success/false[snippets='http-request,http-response']

=== 닉네임 중복 확인
==== 성공
===== 고유한 닉네임인 경우
operation::member/uniqueNickname/success/true[snippets='http-request,http-response']
===== 중복된 닉네임인 경우
operation::member/uniqueNickname/success/false[snippets='http-request,http-response']

=== 회원가입
==== 성공
operation::member/signup/success[snippets='http-request,http-response']
==== 실패
===== 비밀번호 확인이 다른 경우
operation::member/signup/fail/passwordDifferent[snippets='http-request,http-response']
===== 우아한테크코스 회원이 아닐 경우
operation::member/signup/fail/noWooteco[snippets='http-request,http-response']
===== 이미 가입한 회원일 경우
operation::member/signup/fail/alreadySignUp[snippets='http-request,http-response']
===== 인증번호가 틀렸을 경우
operation::member/signup/fail/invalidAuthCode[snippets='http-request,http-response']
===== 이미 존재하는 아이디일 경우
operation::member/signup/fail/duplicateUsername[snippets='http-request,http-response']
===== 이미 존재하는 닉네임일 경우
operation::member/signup/fail/duplicateUsername[snippets='http-request,http-response']

== 로그인/로그아웃

=== 로그인
==== 성공
operation::login/success[snippets='http-request,http-response']
==== 실패
===== 아이디나 비밀번호가 잘못되었을 경우
operation::login/fail[snippets='http-request,http-response']

=== 로그아웃
==== 성공
operation::logout/success[snippets='http-request,http-response']

=== 리프레시
리프레시 관련 컨트롤러 테스트 구현 필요

== 게시판 관리

=== 게시판 목록 조회
==== 성공
operation::board/find/board[snippets='http-request,http-response']

== 글 관리

=== 글 작성하기
==== 성공
operation::post/create/success[snippets='http-request,http-response']
==== 실패
===== 제목에 내용이 없는 경우
operation::post/create/fail/noTitle[snippets='http-request,http-response']
===== 본문에 내용이 없는 경우
operation::post/create/fail/noContent[snippets='http-request,http-response']

=== 글 목록 조회
==== 성공
operation::post/find/all/success[snippets='http-request,http-response']

=== 글 상세 보기
==== 성공
operation::post/find/one/success[snippets='http-request,http-response']
==== 실패
===== 해당 게시물이 없는 경우
operation::post/find/one/fail[snippets='http-request,http-response']

=== 글 수정하기
==== 성공
operation::post/update/success[snippets='http-request,http-response']
==== 실패
===== 게시물 수정 권한이 없는 경우
operation::post/update/fail/noAuth[snippets='http-request,http-response']
===== 제목 혹은 본문에 내용이 없는 경우
operation::post/update/fail/noContent[snippets='http-request,http-response']

=== 글 삭제하기
==== 성공
operation::post/delete/success[snippets='http-request,http-response']
==== 실패
===== 게시물 삭제 권한이 없는 경우
operation::post/delete/fail/noAuth[snippets='http-request,http-response']

== 댓글 관리

=== 댓글 작성
==== 성공
operation::comment/create/success[snippets='http-request,http-response']
==== 실패
===== 댓글 내용이 없는 경우
operation::comment/create/fail/noMessage[snippets='http-request,http-response']

=== 댓글 목록 조회
==== 성공
operation::comment/find/all/success[snippets='http-request,http-response']

=== 댓글 삭제
==== 성공
operation::comment/delete/success[snippets='http-request,http-response']

== 추천
=== 게시글 추천
게시글 추천 관련 컨트롤러 테스트 구현 필요

== 해시태그

=== 해시태그로 검색
==== 성공
operation::search/byHashtag/success[snippets='http-request,http-response']
==== 실패
===== 댓글 내용이 없는 경우
operation::search/byHashtag/fail/noHashtag[snippets='http-request,http-response']

=== 해시태그 목록 조회
==== 성공
operation::hashtags/search/success[snippets='http-request,http-response']

== 신고
게시글/댓글 신고 관련 컨트롤러 테스트 구현 필요
