pipeline{
  agent any

  tools {
      gradle 'gradle'
  }

  stages{
    stage('Ready'){
      steps{
        def allLabels = []

        Jenkins.instance.nodes.each { node ->
          node.assignedLabels.each { label ->
            if (label as String != node.name) {
                allLabels += label
            }      
          }
        }

        println allLabels.unique().join('\n')
      }
    }
  }
}